### PR TITLE
Check in synth script and update google-gax

### LINKED ISSUE #48: Add synth.py and update google-gax

### PR DESCRIPTION
**Pull request by jkwlui**
Fixes #48
ref: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2837

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Review by JustinBeckwith — APPROVED** [review]

**Review by crwilcox — APPROVED** [review]
Seems the generated test is adding an unused helper. If you add that to synth.py to strip this should pass CI.

**Comment by kinwa91** [comment]
@crwilcox any idea how I might strip a block of code?

**Comment by crwilcox** [comment]
@kinwa91 I would do something like the below to find the function and replace it with the empty string.

```
s.replace('file.js',  'function mockSimpleGrpcMethod.*\n(.*\n)*?}', '')
```

**Comment by JustinBeckwith** [comment]
If the generator is creating invalid code, that's a P0.  Please file a P0 here:
https://github.com/googleapis/gapic-generator

Make sure to add the `yoshi` and `priority: P0` labels.

**Comment by kinwa91** [comment]
@crwilcox your regex works great! Thanks!

**Pull request merged**
